services:

  network-deploy-service:
    networks:
      - sneakydate-network

  microservice-base-config:
    extends:
      service: network-deploy-service
    restart: unless-stopped
    environment:
      TZ: "UTC"
      SPRING_JACKSON_SERIALIZATION_WRITE_DATES_AS_TIMESTAMPS: "false"
      SPRING_JACKSON_TIME_ZONE: "UTC"
      JAVA_TOOL_OPTIONS: >
        -Duser.timezone=UTC
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=75
        -XX:InitialRAMPercentage=50
        -XX:MinRAMPercentage=25

  microservice-db-config:
    extends:
      service: network-deploy-service
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "UTC"

  microservice-configserver-config:
    extends:
      service: network-deploy-service
    restart: unless-stopped
    environment:
      TZ: "UTC"

networks:
  sneakydate-network:
